(function(){var f=!0,h=!1,i;
function j(b){var a=this,c=h;a.la=b.useFlashFallback===h?h:!a.ja;a.p=b.statBaseURL;a.w=b.guid;a.s=b.confID;a.b=b.viewableImpressionThreshold;a.va=0;a.R=b.viewableImpressionTime;a.ua=h;a.n=b.customDefinition;a.j=0;a.S=h;a.width=parseInt(b.width,10);a.height=parseInt(b.height,10);a.target=a.e?null:window.parent.document.getElementById(b.divID)||window.frameElement;a.i=a.z=a.visibility.k;a.t=0;a.M=(new Date).getTime();a.N=(new Date).getTime();a.a={visible:0,o:0,hidden:0,Q:0};a.m=f;if(b.fver&&b.minflashversion)this.F=
!!b.fver();else{var d;d=h;if(this.r)for(var e=10;3<=e;e--)d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+e),d=!!parseFloat(d.GetVariable("$version").match(/\b\d+\b/g).join("."));else"undefined"!=typeof navigator.plugins["Shockwave Flash"]&&(d=!!parseFloat(navigator.plugins["Shockwave Flash"].description.substring(15)));this.F=d}if(a.e&&(!window.T||!window.T.qa))"undefined"!==typeof window.mozInnerScreenY?(a.I=a.ca,a.K=a.da):a.F&&!a.C&&a.la?(a.v={},c=f,a.d={$:h},a.g=[],window.ftPagefoldFlashListener=
function(b){b=b.split("-");a.fa(b[0],parseInt(b[1],10))},a.u=a.ga,a.ba()):a.c(this.event.Z);c?b.addEventListener("adonpage",function(){a.d.$=f}):b.addEventListener("adonpage",function(){a.L()})}function k(b){var a="";this.p=b.statBaseURL;this.w=b.guid;this.s=b.confID;this.C=/fox/i.test(navigator.appVersion);a=this.e?window.document.referrer:window.parent.document.location;a=escape(String(a).substr(0,200));this.c("314",a)}
function l(){this.s=this.w=this.p="";this.ia=window!=top;this.e=h;if(this.ia)try{window.parent.document.getElementsByTagName("head")[0].appendChild(window.parent.document.createElement("script"))}catch(b){this.e=f}this.C=/fox/.test(navigator.userAgent);this.r=/MSIE/.test(navigator.userAgent);this.ja=/Safari/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent)}j.prototype=new l;i=j.prototype;i.event={Y:"301",X:"302",B:"303",W:"304",U:"305",V:"306",A:"307",Z:"308",pa:"310",oa:"311",na:"312"};
i.visibility={f:2,l:1,k:0};i.D=[50,175,300,600,1200,3E3];
i.L=function(){function b(){a.m=!document[e]}var a=this,c=this.u(),d=this.event.W,e,g;"undefined"!==typeof document.hidden?(e="hidden",g="visibilitychange"):"undefined"!==typeof document.ra?(e="mozHidden",g="mozvisibilitychange"):"undefined"!==typeof document.sa?(e="msHidden",g="msvisibilitychange"):"undefined"!==typeof document.wa&&(e="webkitHidden",g="webkitvisibilitychange");"undefined"!==typeof e?document.addEventListener(g,b,h):(g=a.e?window:window.parent,a.O(g,"focus",function(){a.m=f}),a.O(g,
"blur",function(){a.m=h}));1===c&&!a.n?d=this.event.Y:0<c&&(d=this.event.X);this.c(d);this.i=this.z=this.J(c);this.P()};
i.P=function(){var b=this,a=(new Date).getTime(),c=a-this.M,d=a-this.N,e=this.u(),g=this.J(e);b.m&&(1==e?this.a.visible+=d:0<e?this.a.o+=d:this.a.hidden+=d,this.n&&(g===this.visibility.f?this.j+=d:this.j<this.R&&(this.j=0),!this.S&&this.j>=this.R&&(this.z===this.visibility.l?this.c(this.event.B):this.c(this.event.A),this.S=f)),g>this.i&&this.ka(g),this.t<this.D.length&&this.h(c)>=this.D[this.t]&&(this.ea(),this.M=a,this.t++),this.N=a);setTimeout(function(){b.P()},249)};
i.ea=function(){var b=[this.h(this.a.visible)];b.push(this.h(this.a.o));b.push(this.h(this.a.hidden));b.push(this.h(this.a.Q));this.c("310",b.join("x"));this.a.visible=0;this.a.o=0;this.a.hidden=0;this.a.Q=0};i.ka=function(b){var a;this.i===this.visibility.k?b===this.visibility.l?a=this.event.U:b===this.visibility.f&&(a=this.event.V):this.i===this.visibility.l&&(b===this.visibility.f&&!this.n)&&(a=this.event.B,this.z===this.visibility.k&&(a=this.event.A));this.i=b;"undefined"!==typeof a&&this.c(a)};
i.u=function(){var b=this.I(),a=this.K();return this.aa(b,a)};i.I=function(){return{x:this.H("Left",this.target),y:this.H("Top",this.target)}};i.H=function(b,a){var c="offset"+b,d=a,e=null!==d?d[c]:0;for("Top"!==b&&"Left"!==b&&this.error("1st argument must be 'Top' or 'Left'");null!==d&&null!==d.offsetParent;)d=d.offsetParent,e+=d[c];return e};
i.K=function(){var b={scrollLeft:0,scrollTop:0,height:0,width:0},a=window.parent;this.e||(a.innerWidth?(b.width=a.innerWidth,b.height=a.innerHeight,b.scrollLeft=a.pageXOffset,b.scrollTop=a.pageYOffset):a.document.documentElement&&a.document.documentElement.clientHeight?(b.width=a.document.documentElement.clientWidth,b.height=a.document.documentElement.clientHeight,b.scrollLeft=a.document.documentElement.scrollLeft,b.scrollTop=a.document.documentElement.scrollTop):a.document.body&&(b.width=a.document.body.clientWidth,
b.height=a.document.body.clientHeight,b.scrollLeft=a.document.body.scrollLeft,b.scrollTop=a.document.body.scrollTop));return b};i.aa=function(b,a){var c=0,d=0,c=Math.max(b.y,a.scrollTop),e=Math.min(b.y+this.height,a.scrollTop+a.height),d=Math.max(b.x,a.scrollLeft),g=Math.min(b.x+this.width,a.scrollLeft+a.width),c=this.G(e-c,this.height),d=this.G(g-d,this.width);return c*d};
i.J=function(b){var a=this.visibility.k;this.n&&b>=this.b?a=this.visibility.f:1===b?a=this.visibility.f:0<b&&(a=this.visibility.l);return a};i.ca=function(){return{x:window.mozInnerScreenX,y:window.mozInnerScreenY}};i.da=function(){return{scrollLeft:window.screenX,scrollTop:window.screenY,height:window.outerHeight,width:window.outerWidth}};i.ga=function(){var b=0,a=0,c;for(c in this.v)b+=300>this.v[c]?1:0;return a=0.5===this.b?1>b?0:5>b?0.1:9>b?this.b:1:1>b?0:8>b?0.1:12>b?this.b:1};
i.fa=function(b,a){var c=0;this.v[b]=a;this.d[b]=f;for(var d in this.d)this.d[d]||c++;0===c&&(this.L(),this.d.ta=h)};
i.ba=function(){function b(a){return""+Math.round(a)}var a=Math.sqrt(this.b),c=[b(this.width*(1-a)),b(this.width*(1-this.b)),b(this.width*this.b),b(this.width*a)],a=[b(this.height*(1-a)),b(this.height*(1-this.b)),b(this.height*this.b),b(this.height*a)];this.g=[{id:"0",left:"0",top:a[0]},{id:"1",left:"0",top:a[3]},{id:"2",left:c[0],top:"0"},{id:"3",left:c[0],top:""+(this.height-1)},{id:"4",left:c[1],top:a[1]},{id:"5",left:c[1],top:a[2]},{id:"6",left:c[2],top:a[1]},{id:"7",left:c[2],top:a[2]},{id:"8",
left:c[3],top:"0"},{id:"9",left:c[3],top:""+(this.height-1)},{id:"10",left:""+(this.width-1),top:a[0]},{id:"11",left:""+(this.width-1),top:a[3]}];0.5===this.b&&(this.g=[{id:"0",left:"0",top:a[0]},{id:"1",left:"0",top:a[3]},{id:"2",left:c[0],top:"0"},{id:"3",left:c[0],top:+(this.height-1)},{id:"4",left:""+this.width/2,top:""+this.height/2},{id:"5",left:c[3],top:"0"},{id:"6",left:c[3],top:""+(this.height-1)},{id:"7",left:""+(this.width-1),top:a[0]},{id:"8",left:""+(this.width-1),top:a[3]}]);c=0;for(a=
this.g.length;c<a;c++){this.d[this.g[c].id]=h;var d=this.g[c],e=void 0,g="position: absolute; top: "+d.top+"px;",m=this.ha(d.id),g=g+(" width: "+this.q.width+"px;"),g=g+(" height: "+this.q.height+"px;"),g=g+(" left : "+d.left+"px; z-index: -1;");this.r?(e='<div style="@STYLE@">@FLASH@</div>'.replace("@STYLE@",g).replace("@FLASH@",m),document.body.insertAdjacentHTML("afterbegin",e)):(e=document.createElement("div"),e.style.cssText=g,e.innerHTML=m,document.body.appendChild(e))}};
i.ha=function(b){var a=this.q,c=a.name+b,d;d="<OBJECT "+(this.r?'classid = "clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'data="'+a.path+'" type="application/x-shockwave-flash"');d=d+(' ID="'+c+'" name="'+c+'"')+(' width="'+a.width+'" height="'+a.height+'" style="float:left;">');d+='<PARAM NAME=movie VALUE="'+a.path+'"/>';d+='<PARAM NAME=FlashVars VALUE="identifier='+b+'"/>';d+='<PARAM NAME=quality VALUE="autohigh"/>';d+='<PARAM NAME=wmode VALUE="'+a.ma+'"/>';d+='<PARAM NAME="allowScriptAccess" value="always"/>';
d+='<PARAM NAME="allowFullScreen" value="true"/>';return d+="</OBJECT>"};i.q={path:"//"+("s"===window.location.protocol[4]?"secure":"cdn")+".flashtalking.com/pageFold/pagefold.swf",name:"ftPF",width:1,height:2,ma:"opaque"};i.G=function(b,a){return Math.max(Math.ceil(10*(b/a))/10,0)};i.h=function(b){return Math.ceil(b/100)};k.prototype=new l;l.prototype.c=function(b,a){var c=[""+this.p+this.s];c.push(b);c.push("0");c.push(this.w);c.push(this.random());a&&c.push(a);this.p&&((new Image).src=c.join("-"))};
l.prototype.random=function(b){return Math.floor(Math.random()*(b||1E9))};l.prototype.error=function(){};l.prototype.O=function(b,a,c){"function"===typeof b.addEventListener?b.addEventListener(a,c,h):b.attachEvent("on"+a,c)};window.ftPageFold_v3=function(b){new k(b);new j(b)};}());
